openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /actions:
    post:
      summary: Add an action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Action"
      responses:
        "200":
          description: Action performed
    get:
      summary: List actions
      responses:
        "200":
          description: A list of actions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListActionsResponse"
components:
  schemas:
    ListActionsResponse:
      type: object
      properties:
        actions:
          type: array
          items:
            $ref: "#/components/schemas/Action"
    Action:
      type: object
      discriminator:
        propertyName: type
        mapping:
          "create_object": "#/components/schemas/CreateObject"
          "update_object": "#/components/schemas/UpdateObject"
          "delete_object": "#/components/schemas/DeleteObject"
          "delete_all_objects": "#/components/schemas/DeleteAllObjects"
      oneOf:
        - $ref: "#/components/schemas/CreateObject"
        - $ref: "#/components/schemas/UpdateObject"
        - $ref: "#/components/schemas/DeleteObject"
        - $ref: "#/components/schemas/DeleteAllObjects"
    CreateObject:
      type: object
      properties:
        type:
          type: string
        object:
          $ref: "#/components/schemas/Object"
    UpdateObject:
      type: object
      properties:
        type:
          type: string
        object:
          $ref: "#/components/schemas/Object"
    DeleteObject:
      type: object
      properties:
        type:
          type: string
        id:
          type: string
    DeleteAllObjects:
      type: object
      properties:
        type:
          type: string
    Object:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/ObjectType"
        id:
          type: string
        name:
          type: string
    ObjectType:
      type: string
      enum: ["user", "group"]
