linters:
  enable:
  - exhaustive
  - gochecksumtype
linters-settings:
  exhaustive:
    check:
      - switch
      - map
    ignore-enum-members: "+_Unknown"
  gochecksumtype:
    default-signifies-exhaustive: false
