linters:
  enable:
    - exhaustive
    - gochecksumtype
    - exhaustruct
linters-settings:
  exhaustive:
    check:
      - switch
      - map
  gochecksumtype:
    default-signifies-exhaustive: false
